detectors:
  TooManyStatements:
    enabled: false
  LongParameterList:
    max_params: 5
  DuplicateMethodCall:
    allow_calls:
      - 'format.*'

directories:
  'app':
    IrresponsibleModule:
      enabled: false
  'app/policies':
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  'app/graphql/mutations':
    UtilityFunction:
      enabled: false
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  'db/migrate':
    FeatureEnvy:
      enabled: false
    IrresponsibleModule:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false
  'app/controllers':
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  'app/jobs':
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  'app/helpers':
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  'app/mailers':
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  'config':
    IrresponsibleModule:
      enabled: false
  'db':
    LongParameterList:
      enabled: false
    IrresponsibleModule:
      enabled: false
  'test':
    UtilityFunction:
      enabled: false
    IrresponsibleModule:
      enabled: false
